// POST /functions/v1/generate — Laszlo text runtime (ADR 0014).
//
// One endpoint, four modes:
//   - hotspot   : batch JSON. Personalized text for the N hotspots of an artwork,
//                 requested when the visitor opens the artwork (never on tap).
//   - ask       : SSE stream. Free-form Q&A, placed-point question, or hotspot follow-up.
//   - persona   : JSON. The hidden onboarding call (S5): selections -> persona_summary.
//   - followups : JSON. Three suggested next questions for the current context.
//
// Grounding is ALWAYS re-read server-side from the `notice` table: the client sends
// `artwork_id`, never the notices themselves (untrusted client = no trusted facts).
//
// ponytail: the LLM is STUBBED via the `stub*` helpers in lib.ts. Swap them for an
// OpenAI-compatible call (base_url + key from env) once LLM_API_KEY is in .env. The
// HTTP contract (request/response shapes) does not change — only text production does.
// Everything else here (parsing, grounding reads, SSE framing, response shapes) is real.

import { createClient } from "jsr:@supabase/supabase-js@2";
import {
  type HotspotRow,
  type NoticeRow,
  noticesToSources,
  stubAskText,
  stubFollowups,
  stubHotspotText,
  stubPersona,
} from "./lib.ts";

// CORS: the app calls this function cross-origin, so we must answer the preflight
// (OPTIONS) and echo permissive headers. Tighten the origin for production.
const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

/** Build a JSON Response with CORS headers. */
const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, "Content-Type": "application/json" },
  });

/**
 * Supabase client scoped to this request. URL and anon key are injected automatically
 * into deployed edge functions; locally they come from the env. The anon key is enough
 * because `notice`/`hotspot` are public-read (same access the app has).
 */
function db() {
  return createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_ANON_KEY")!,
  );
}

/** Read all grounding notices for an artwork (one indexed read, small payload). */
async function readNotices(artworkId: string): Promise<NoticeRow[]> {
  const { data } = await db()
    .from("notice")
    .select("id, lang, source, text")
    .eq("artwork_id", artworkId);
  return (data ?? []) as NoticeRow[];
}

Deno.serve(async (req) => {
  // CORS preflight.
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST") return json({ message: "POST only" }, 405);

  // Parse the request body. `any` here because the shape depends on `mode`.
  let body: Record<string, any>;
  try {
    body = await req.json();
  } catch {
    return json({ message: "invalid JSON" }, 400);
  }

  // Fields common to every mode. `request_id` is generated by the app and echoed back
  // so the app can correlate batch requests with their responses.
  const { mode, request_id = null, lang = "fr", artwork_id } = body;

  // --- persona: no grounding needed, just turn the onboarding selections into a summary.
  if (mode === "persona") {
    return json({
      type: "done",
      request_id,
      persona_summary: stubPersona(body.onboarding ?? {}, lang),
    });
  }

  // Every remaining mode is grounded on an artwork's notices.
  if (!artwork_id) return json({ message: "artwork_id is required" }, 400);
  const notices = await readNotices(artwork_id);
  const sources = noticesToSources(notices);

  // --- hotspot: one batch request returns the text for every requested hotspot.
  if (mode === "hotspot") {
    const ids: string[] = body.hotspot_ids ?? [];
    const { data } = await db()
      .from("hotspot")
      .select("id, title, aspect, narration_text")
      .in("id", ids);
    const rows = (data ?? []) as HotspotRow[];

    // Preserve the requested order; mark any missing id as an error item.
    const items = ids.map((id) => {
      const h = rows.find((r) => r.id === id);
      return h
        ? {
          hotspot_id: id,
          status: "ready",
          text: stubHotspotText(h, lang),
          message: null,
          sources,
        }
        : {
          hotspot_id: id,
          status: "error",
          text: null,
          message: "hotspot not found",
          sources: [],
        };
    });
    return json({ type: "done", request_id, items });
  }

  // --- followups: three suggested questions for the current context.
  if (mode === "followups") {
    return json({ type: "done", request_id, questions: stubFollowups(lang) });
  }

  // --- ask: stream the answer as Server-Sent Events so the app (and TTS) can start
  // consuming before generation finishes.
  if (mode === "ask") {
    const question: string = body.question ?? "";
    const text = stubAskText(question, lang, notices.length);
    const encoder = new TextEncoder();

    const stream = new ReadableStream({
      async start(controller) {
        const send = (event: unknown) =>
          controller.enqueue(
            encoder.encode(`data: ${JSON.stringify(event)}\n\n`),
          );

        // ponytail: word-by-word loop simulates the LLM token stream. Replace with the
        // real provider stream; keep emitting `delta` events then a final `done`.
        for (const word of text.split(" ")) {
          send({ type: "delta", request_id, delta: word + " " });
          await new Promise((r) => setTimeout(r, 30));
        }
        send({ type: "done", request_id, text, sources });
        controller.close();
      },
    });

    return new Response(stream, {
      headers: {
        ...CORS,
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
      },
    });
  }

  return json({ message: `unknown mode: ${mode}` }, 400);
});
