// POST /functions/v1/generate — Laszlo text runtime (ADR 0014).
//
// One endpoint, four modes:
//   - hotspot   : batch JSON. Personalized text for the N hotspots of an artwork,
//                 requested when the visitor opens the artwork (never on tap).
//   - ask       : SSE stream. Free-form Q&A, placed-point question, or hotspot follow-up.
//   - persona   : JSON. The hidden onboarding call (S5): selections -> persona_summary.
//   - followups : JSON. Three suggested next questions for the current context.
//
// Grounding is ALWAYS re-read server-side from the `notice` table: the client sends
// `artwork_id`, never the notices themselves (untrusted client = no trusted facts).
//
// The LLM is a real OpenAI-compatible call (Scaleway, see llm.ts). Each mode falls
// back to a deterministic stub if the model call fails, so a demo never shows a blank.

import { CORS, jsonResponse, preflight } from "../_shared/http.ts";
import { anonClient } from "../_shared/supabase.ts";
import { complete, type Msg, streamDeltas } from "./llm.ts";
import {
  askPrompt,
  buildGrounding,
  followupsPrompt,
  hotspotPrompt,
  type HotspotRow,
  type NoticeRow,
  noticesToSources,
  parseFollowups,
  personaPrompt,
  stubFollowups,
  stubHotspotText,
  stubPersona,
  systemPrompt,
} from "./lib.ts";

/** Read all grounding notices for an artwork (one indexed read, small payload). */
async function readNotices(artworkId: string): Promise<NoticeRow[]> {
  const { data } = await anonClient()
    .from("notice")
    .select("id, lang, source, text")
    .eq("artwork_id", artworkId);
  return (data ?? []) as NoticeRow[];
}

/** Keep only well-formed conversation turns from the client-held history. */
function historyMessages(history: unknown): Msg[] {
  if (!Array.isArray(history)) return [];
  return history
    .filter((m) =>
      m && (m.role === "user" || m.role === "assistant") &&
      typeof m.content === "string"
    )
    .map((m) => ({ role: m.role, content: m.content }));
}

Deno.serve(async (req) => {
  // CORS preflight.
  const pre = preflight(req);
  if (pre) return pre;
  if (req.method !== "POST") return jsonResponse({ message: "POST only" }, 405);

  // Parse the request body. `any` here because the shape depends on `mode`.
  let body: Record<string, any>;
  try {
    body = await req.json();
  } catch {
    return jsonResponse({ message: "invalid JSON" }, 400);
  }

  // Fields common to every mode. `request_id` is generated by the app and echoed back
  // so the app can correlate batch requests with their responses.
  const {
    mode,
    request_id = null,
    lang = "fr",
    artwork_id,
    profile,
    steering,
  } = body;

  // --- persona: no grounding; turn onboarding selections into a reusable summary.
  if (mode === "persona") {
    const onboarding = body.onboarding ?? {};
    let persona_summary: string;
    try {
      persona_summary = await complete(
        [
          {
            role: "system",
            content: "You write concise museum-visitor personas.",
          },
          { role: "user", content: personaPrompt(onboarding, lang) },
        ],
        0.3,
      );
    } catch {
      persona_summary = stubPersona(onboarding, lang); // fallback: raw selections
    }
    return jsonResponse({ type: "done", request_id, persona_summary });
  }

  // Every remaining mode is grounded on an artwork's notices.
  if (!artwork_id) {
    return jsonResponse({ message: "artwork_id is required" }, 400);
  }
  const notices = await readNotices(artwork_id);
  const sources = noticesToSources(notices);
  const grounding = buildGrounding(notices);
  const system = systemPrompt(lang, profile, steering);

  // --- hotspot: one batch request returns the text for every requested hotspot.
  if (mode === "hotspot") {
    const ids: string[] = body.hotspot_ids ?? [];
    const { data } = await anonClient()
      .from("hotspot")
      .select("id, title, aspect, narration_text")
      .in("id", ids);
    const rows = (data ?? []) as HotspotRow[];

    // One LLM call per hotspot, in parallel. A per-hotspot failure falls back to the
    // hand-written seed (still "ready" — the demo must always show something).
    const items = await Promise.all(ids.map(async (id) => {
      const h = rows.find((r) => r.id === id);
      if (!h) {
        return {
          hotspot_id: id,
          status: "error",
          text: null,
          message: "hotspot not found",
          sources: [],
        };
      }
      try {
        const text = await complete([
          { role: "system", content: system },
          {
            role: "user",
            content: hotspotPrompt(h, grounding, body.history_summary),
          },
        ]);
        return {
          hotspot_id: id,
          status: "ready",
          text,
          message: null,
          sources,
        };
      } catch {
        return {
          hotspot_id: id,
          status: "ready",
          text: stubHotspotText(h, lang),
          message: null,
          sources,
        };
      }
    }));
    return jsonResponse({ type: "done", request_id, items });
  }

  // --- followups: three suggested questions for the current context.
  if (mode === "followups") {
    let questions: string[];
    try {
      const raw = await complete([
        { role: "system", content: system },
        {
          role: "user",
          content: followupsPrompt(grounding, lang, body.history_summary),
        },
      ], 0.7);
      questions = parseFollowups(raw);
      if (questions.length === 0) questions = stubFollowups(lang);
    } catch {
      questions = stubFollowups(lang);
    }
    return jsonResponse({ type: "done", request_id, questions });
  }

  // --- ask: stream the answer as Server-Sent Events so the app (and TTS) can start
  // consuming before generation finishes.
  if (mode === "ask") {
    const question: string = body.question ?? "";
    const messages: Msg[] = [
      { role: "system", content: system },
      ...historyMessages(body.history),
      {
        role: "user",
        content: askPrompt(question, grounding, {
          hotspotId: body.hotspot_id,
          point: body.point,
        }),
      },
    ];
    const encoder = new TextEncoder();

    const stream = new ReadableStream({
      async start(controller) {
        const send = (event: unknown) =>
          controller.enqueue(
            encoder.encode(`data: ${JSON.stringify(event)}\n\n`),
          );
        let full = "";
        try {
          for await (const delta of streamDeltas(messages)) {
            full += delta;
            send({ type: "delta", request_id, delta });
          }
          send({ type: "done", request_id, text: full, sources });
        } catch (e) {
          // If we already streamed something, close cleanly with what we have;
          // otherwise surface the error so the app can show a fallback.
          if (full) send({ type: "done", request_id, text: full, sources });
          else send({ type: "error", request_id, message: String(e) });
        }
        controller.close();
      },
    });

    return new Response(stream, {
      headers: {
        ...CORS,
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
      },
    });
  }

  return jsonResponse({ message: `unknown mode: ${mode}` }, 400);
});
