// POST /functions/v1/generate — Laszlo text runtime (ADR 0014).
//
// One endpoint, five modes:
//   - overview  : JSON. Opening intro for the whole artwork shown when the visitor
//                 enters the artwork view (the "✦ L'œuvre" virtual hotspot). Fired once
//                 alongside the hotspot batch; displayed immediately on arrival.
//   - hotspot   : batch JSON. Personalized text for the N hotspots of an artwork,
//                 requested when the visitor opens the artwork (never on tap).
//   - ask       : SSE stream. Free-form Q&A, placed-point question, or hotspot follow-up.
//   - persona   : JSON. The hidden onboarding call (S5): selections -> persona_summary.
//   - followups : JSON. Three suggested next questions for the current context.
//
// Grounding is ALWAYS re-read server-side from the `notice` table: the client sends
// `artwork_id`, never the notices themselves (untrusted client = no trusted facts).
//
// The LLM is a real OpenAI-compatible call (Scaleway, see llm.ts). Each mode falls
// back to a deterministic stub if the model call fails, so a demo never shows a blank.
//
// Routing/validation/fallback live in `handle(req, deps)`; the external boundaries
// (DB reads, LLM) are injected via `deps` so tests can drive every scenario offline.

import { CORS, jsonResponse, preflight } from "../_shared/http.ts";
import { anonClient } from "../_shared/supabase.ts";
import { complete, type Msg, streamDeltas } from "./llm.ts";
import {
  buildGrounding,
  type HotspotRow,
  type NoticeRow,
  noticesToSources,
  parseFollowups,
  selectPivotNotices,
  stubFollowups,
  stubHotspotText,
  stubOverviewText,
  stubPersona,
} from "./lib.ts";
import {
  askPrompt,
  followupsPrompt,
  hotspotPrompt,
  overviewPrompt,
  personaPrompt,
  systemPrompt,
} from "./prompts.ts";

/** External boundaries the handler depends on (real impls below, fakes in tests). */
export type GenerateDeps = {
  readNotices: (artworkId: string) => Promise<NoticeRow[]>;
  readHotspots: (ids: string[]) => Promise<HotspotRow[]>;
  complete: (messages: Msg[], temperature?: number) => Promise<string>;
  streamDeltas: (
    messages: Msg[],
    temperature?: number,
  ) => AsyncIterable<string>;
};

export const realDeps: GenerateDeps = {
  async readNotices(artworkId) {
    const { data } = await anonClient()
      .from("notice").select("id, lang, source, text").eq(
        "artwork_id",
        artworkId,
      );
    return (data ?? []) as NoticeRow[];
  },
  async readHotspots(ids) {
    const { data } = await anonClient()
      .from("hotspot").select("id, title, aspect, narration_text").in(
        "id",
        ids,
      );
    return (data ?? []) as HotspotRow[];
  },
  complete,
  streamDeltas,
};

/** Keep only well-formed conversation turns from the client-held history. */
function historyMessages(history: unknown): Msg[] {
  if (!Array.isArray(history)) return [];
  return history
    .filter((m) =>
      m && (m.role === "user" || m.role === "assistant") &&
      typeof m.content === "string"
    )
    .map((m) => ({ role: m.role, content: m.content }));
}

export async function handle(
  req: Request,
  deps: GenerateDeps,
): Promise<Response> {
  const pre = preflight(req);
  if (pre) return pre;
  if (req.method !== "POST") return jsonResponse({ message: "POST only" }, 405);

  let body: Record<string, any>;
  try {
    body = await req.json();
  } catch {
    return jsonResponse({ message: "invalid JSON" }, 400);
  }

  // `request_id` is generated by the app and echoed back so it can correlate responses.
  const {
    mode,
    request_id = null,
    lang = "fr",
    artwork_id,
    profile,
    steering,
  } = body;

  // --- persona: no grounding; turn onboarding selections into a reusable summary.
  if (mode === "persona") {
    const onboarding = body.onboarding ?? {};
    let persona_summary: string;
    try {
      persona_summary = await deps.complete([
        {
          role: "system",
          content:
            "You turn a few onboarding signals into a vivid, useful portrait of one" +
            " museum visitor — the kind of brief that helps a guide find the right voice.",
        },
        { role: "user", content: personaPrompt(onboarding, lang) },
      ], 0.3);
    } catch {
      persona_summary = stubPersona(onboarding, lang); // fallback: raw selections
    }
    return jsonResponse({ type: "done", request_id, persona_summary });
  }

  // Every remaining mode is grounded on an artwork's notices.
  if (!artwork_id) {
    return jsonResponse({ message: "artwork_id is required" }, 400);
  }
  // EN-pivot: ground (and cite) a single language so the model doesn't see redundant
  // bilingual facts. Sources reflect exactly what grounded the answer.
  const notices = selectPivotNotices(await deps.readNotices(artwork_id));
  const sources = noticesToSources(notices);
  const grounding = buildGrounding(notices);
  const system = systemPrompt(lang, profile, steering);

  // --- overview: single JSON call that introduces the whole artwork. Fired once when
  //     the visitor enters the artwork view alongside the hotspot batch. The result is
  //     the "✦ L'œuvre" virtual hotspot shown by default in the app.
  if (mode === "overview") {
    let text: string;
    try {
      text = await deps.complete([
        { role: "system", content: system },
        { role: "user", content: overviewPrompt(grounding, body.history_summary) },
      ]);
    } catch {
      text = stubOverviewText(lang); // fallback: deterministic placeholder
    }
    return jsonResponse({ type: "done", request_id, text, sources });
  }

  // --- hotspot: one batch request returns the text for every requested hotspot.
  if (mode === "hotspot") {
    const ids: string[] = body.hotspot_ids ?? [];
    const rows = await deps.readHotspots(ids);
    // One LLM call per hotspot, in parallel. A per-hotspot failure falls back to the
    // hand-written seed (still "ready" — the demo must always show something).
    const items = await Promise.all(ids.map(async (id) => {
      const h = rows.find((r) => r.id === id);
      if (!h) {
        return {
          hotspot_id: id,
          status: "error",
          text: null,
          message: "hotspot not found",
          sources: [],
        };
      }
      try {
        const text = await deps.complete([
          { role: "system", content: system },
          {
            role: "user",
            content: hotspotPrompt(h, grounding, body.history_summary),
          },
        ]);
        return {
          hotspot_id: id,
          status: "ready",
          text,
          message: null,
          sources,
        };
      } catch {
        return {
          hotspot_id: id,
          status: "ready",
          text: stubHotspotText(h, lang),
          message: null,
          sources,
        };
      }
    }));
    return jsonResponse({ type: "done", request_id, items });
  }

  // --- followups: three suggested questions for the current context.
  if (mode === "followups") {
    let questions: string[];
    try {
      const raw = await deps.complete([
        { role: "system", content: system },
        {
          role: "user",
          content: followupsPrompt(grounding, lang, body.history_summary),
        },
      ], 0.7);
      questions = parseFollowups(raw);
      if (questions.length === 0) questions = stubFollowups(lang);
    } catch {
      questions = stubFollowups(lang);
    }
    return jsonResponse({ type: "done", request_id, questions });
  }

  // --- ask: stream the answer as SSE so the app (and TTS) can start before it finishes.
  if (mode === "ask") {
    const question: string = body.question ?? "";
    // history_summary carries the older turns once the app caps `history` (8 msgs).
    const summary: string | null = body.history_summary ?? null;
    const messages: Msg[] = [
      { role: "system", content: system },
      ...(summary
        ? [
          {
            role: "system",
            content: `Earlier in this visit: ${summary}`,
          } as Msg,
        ]
        : []),
      ...historyMessages(body.history),
      {
        role: "user",
        content: askPrompt(question, grounding, {
          hotspotId: body.hotspot_id,
          point: body.point,
        }),
      },
    ];
    const encoder = new TextEncoder();
    const stream = new ReadableStream({
      async start(controller) {
        const send = (e: unknown) =>
          controller.enqueue(encoder.encode(`data: ${JSON.stringify(e)}\n\n`));
        let full = "";
        try {
          for await (const delta of deps.streamDeltas(messages)) {
            full += delta;
            send({ type: "delta", request_id, delta });
          }
          send({ type: "done", request_id, text: full, sources });
        } catch (e) {
          // Already streamed something -> close cleanly; otherwise surface the error.
          if (full) send({ type: "done", request_id, text: full, sources });
          else send({ type: "error", request_id, message: String(e) });
        }
        controller.close();
      },
    });
    return new Response(stream, {
      headers: {
        ...CORS,
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
      },
    });
  }

  return jsonResponse({ message: `unknown mode: ${mode}` }, 400);
}

// Start the server only when run as the entry point (deployed / `deno run`),
// not when imported by tests.
if (import.meta.main) Deno.serve((req) => handle(req, realDeps));
